CREATE TABLE `t_database_maintablechart` (
  `CHART_ID` decimal(19,0) NOT NULL,
  `TABLE_ID` decimal(19,0) DEFAULT NULL,
  `CHART_TITLE` varchar(255) DEFAULT NULL,
  `XAXIS_NAME` varchar(255) DEFAULT NULL,
  `YAXIS_NAME` varchar(255) DEFAULT NULL,
  `SERIES_NAME` varchar(255) DEFAULT NULL,
  `XAXIS_VALUE` varchar(255) DEFAULT NULL,
  `YAXIS_VALUE` varchar(255) DEFAULT NULL,
  `ISEXTEND` varchar(255) DEFAULT NULL,
  `EXTENDSQL` varchar(2000) DEFAULT NULL,
  `APP_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CHART_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

